### ISSUE TITLE
Error parsing float numbers

### ISSUE THREAD

**Issue by soulmachine** [serde-rs/json#891] opened 2022-05-30 23:19 UTC
The library can not parse float numbers correctly, see the following code snipet:

```rust
use std::collections::HashMap;
use serde_json::Value;

fn main() {
    let obj = serde_json::from_str::<HashMap<String, Value>>(r#"{"n": 1289.8126064735945}"#).unwrap();
    println!("{}", obj["n"]); // should be 1289.8126064735945
    println!("{}", "1289.8126064735945".parse::<f64>().unwrap());
}
```

code link: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d941748303918dac4e3ad3e4b48df148>

From the code above, we can see that the built-in `parse()` function can parse it correctly, while the `serde_json` library can NOT.

**Comment by dtolnay** [comment] 2022-05-30 23:39
Closing as a duplicate of #707.

**Closed by dtolnay** 2022-05-30 23:39 UTC
