### ISSUE TITLE
Long floats do not deserialize exactly when `float_roundtrip` is not enabled

### ISSUE THREAD

**Issue by nigeltao** [serde-rs/json#707] opened 2020-09-05 12:16 UTC
This program:

```
fn main() -> Result<(), Box<serde_json::error::Error>> {
    let x0 = 122.416294033786585;
    let s = "122.416294033786585";
    let x1: f64 = serde_json::from_str(s)?;
    println!("{}\n{}\nEqual: {}\n", x0, x1, x0 == x1);
    Ok(())
}
```

Prints:

```
122.41629403378658
122.4162940337866
Equal: false
```

I understand that both `etc658` and `etc66` can only be approximated by `f64`, and the closest `f64` numbers (as 64 bits and as precise decimal) are:

```
0x405E9AA48FBB2888: 122.4162940337865848050569184124469757080078125
0x405E9AA48FBB2889: 122.4162940337865990159116336144506931304931640625
```

Still, I would expect `x0` and `x1`, both `f64` values, to be equal. Whatever rounding algorithm is good for the Rust compiler is good for `serde_json`, right?

**Comment by ta32** [comment] 2020-10-23 11:56
`       let test = "10587.436593658975";
        let b: f64 = serde_json::from_str(test).unwrap();
        let a: f64 = test.parse().unwrap();
`
this also doesn't work. a =10587.436593658975
b = 10587.436593658977

name = "serde_json"
version = "1.0.59"

**Comment by pimeys** [comment] 2020-11-04 14:26
We got a bug filed where a user tries to use numbers in a JSON object, that loses accuracy:

```rust
fn main() {
    let x0 = 0.9215686321258545;
    let s = "0.9215686321258545";
    let x1: f64 = serde_json::from_str(s).unwrap();

    println!("{}\n{}\nEqual: {}\n", x0, x1, x0 == x1);
}
```

Prints:

```
0.9215686321258545
0.9215686321258544
Equal: false
```

**Comment by pimeys** [comment] 2020-11-04 14:40
Nevermind, enabling `float_roundtrip` feature fixes the issue.

**Comment by nigeltao** [comment] 2021-08-22 06:07
OK, but I see that `float_roundtrip` ["comes at an approximately 2x performance cost for parsing floats compared to the default best-effort precision"](https://github.com/serde-rs/json/blob/6346bb30037f31ea69b9a4eb029875e23521681c/Cargo.toml#L60-L62).

**Comment by dtolnay** [comment] 2022-01-22 20:27
I'll close this as being the intended behavior &mdash; you'll need to enable `float_roundtrip` if you'd like the slower precise parser.

**Closed by dtolnay** 2022-01-22 20:27 UTC
