### ISSUE TITLE
Failure deserializing from a reader into an untagged enum containing borrowed data

### ISSUE THREAD

**Issue by argv-minus-one** [serde-rs/json#573] opened 2019-10-02 07:24 UTC
I've found a case where serde_json deserializes from a `[u8]` fine, but deserializing from a `Read` fails. It happens when deserializing an untagged enum containing borrowed strings, with both newtype and struct variants, like so:

```rust
#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum TestEnum<'a> {
	PlainString(&'a str),
	StructWithString {
		s: &'a str
	}
}
```

This only fails when the strings in the enum are borrowed from the deserializer *and* the deserializer is created with `serde_json::Deserializer::from_reader`. It doesn't fail if:

* the strings are changed from `&str` to `String`, or
* the deserializer is created with `from_slice` instead.

Here's a complete demonstration of this issue, which can be run with [cargo-script](https://crates.io/crates/cargo-script):

```rust
//! ```cargo
//! [package]
//! edition = "2018"
//! 
//! [dependencies]
//! serde = { version = "1.0.101", features = ["derive"] }
//! serde_json = "1.0.40"
//! ```

#[macro_use]
extern crate serde;

use serde::Deserialize;
use serde_json::Deserializer;

#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum TestEnum<'a> {
	PlainString(&'a str),
	StructWithString {
		s: &'a str
	}
}

const TEST_JSON: &[u8] = b"[
	\"foo\",
	{\"s\": \"bar\"}
]";

fn try_reading(as_reader: bool) -> Result<(), serde_json::Error> {
	let objs: Vec<TestEnum> = {
		if as_reader {
			Vec::<TestEnum>::deserialize(&mut Deserializer::from_reader(TEST_JSON))?
		}
		else {
			Vec::<TestEnum>::deserialize(&mut Deserializer::from_slice(TEST_JSON))?
		}
	};

	println!(
		"Deserializing from {} successful. Result: {:#?}",
		match as_reader {
			false => "slice",
			true => "reader"
		},
		objs
	);

	Ok(())
}

fn main() {
	for as_reader in [false, true].iter() {
		if let Err(error) = try_reading(*as_reader) {
			println!(
				"Deserializing from {} failed. Error: {}",
				match as_reader {
					false => "slice",
					true => "reader"
				},
				error
			);
		}
	}
}
```

This program tries to deserialize the enum using deserializers created with `from_slice` and `from_reader`, and reports the success or failure of each attempt. The output is:

```
Deserializing from slice successful. Result: [
    PlainString(
        "foo",
    ),
    StructWithString {
        s: "bar",
    },
]
Deserializing from reader failed. Error: data did not match any variant of untagged enum TestEnum at line 3 column 2
```

If the enum is changed to have `String`s instead of `&str`s, then both attempts succeed:

```
Deserializing from slice successful. Result: [
    PlainString(
        "foo",
    ),
    StructWithString {
        s: "bar",
    },
]
Deserializing from reader successful. Result: [
    PlainString(
        "foo",
    ),
    StructWithString {
        s: "bar",
    },
]
```

**Comment by dtolnay** [comment] 2019-10-03 20:52
Closing because this is the intended behavior -- i/o streams do not provide zero copy behavior. You can tell from https://doc.rust-lang.org/std/io/trait.Read.html having no borrow-based methods, all of the trait methods involve copying bytes out of the data source.

**Closed by dtolnay** 2019-10-03 20:52 UTC
