### ISSUE TITLE
Always serialize f32's as f64's

### ISSUE THREAD

**Issue by orlp** [serde-rs/json#1022] opened 2023-06-04 11:33 UTC
I noticed that `serde_json` prints `f32`s using `f32` precision. This is problematic in multiple ways.

1. The internal JSON representation always stores the value as an `f64`. This means that going through the `Value` representation before serializing changes the outcome:
    ```rust
    use serde::{Serialize, Deserialize};
    
    #[derive(Serialize, Deserialize, Debug)]
    struct Foo {
        f: f32,
    }
    
    fn main() {
        let f = f32::from_bits(0x3f800001);
        let foo = Foo { f };
        let foo_json = serde_json::to_value(&foo).unwrap();
        println!("{}", serde_json::to_string(&foo).unwrap());
        println!("{}", serde_json::to_string(&foo_json).unwrap());
    }
    ```
    ```json
    {"f":1.0000001}
    {"f":1.0000001192092896}
    ```

2. More seriously, this loses precision for any consumer that parses the `f32`s as a `f64`. This is a subtle point, so allow me to explain with an example.

   Consider the floating point value `f32::from_bits(0x3f800001)`. Rust will print it as `1.0000001` as an `f32`, or `1.0000001192092896` as an `f64`. Both of those aren't the correct value, but truncated. The real value of that floating point object is `1 + 2^-23 = 1.00000011920928955078125`. This value is **exactly** representable in both `f32` and `f64` (the `f64`s are a strict superset of the `f32`s). Yet, when one parses `1.0000001` as a `f64`, you get a **different** value than it.

    None of this matters if you strictly use the serialize/deserialize functionality directly on a struct as everything round-trips. But if you go through the `Value` representation as an intermediate, or parse the data using another language such as Python or Javascript, things blow up.  E.g. Python always parses JSON as 64-bit floats. And that's where things go wrong:
  
    ```python
    >>> float("1.00000011920928955078125") - float("1.0000001192092896")
    0.0
    >>> float("1.00000011920928955078125") - float("1.0000001")
    1.9209289492394532e-08
    ```

    I would like to emphasize that this gives *the wrong result*. This isn't a case of '`f32` has less precision'. It means that you deserialize a value different than `f32::from_bits(0x3f800001)` on the Python/Javascript side, despite the original value being perfectly representable without loss!

My suggestion would be to simply always serialize `f32`s as `f64`s, because you can not control how the consumer parses the JSON. It is the only solution if you want `f32` values to be correctly parsed in languages such as Python / Javascript.

**Comment by dtolnay** [comment] 2023-06-07 20:43
1. For 1, I would recommend using serde_json with `features = ["arbitrary_precision"]`. That way `serde_json::to_string(x)?` and `serde_json::to_value(x)?.to_string()` produce the same JSON numbers.

2. I think this is working as intended. It is not a goal that f32 -&gt; json -&gt; f64 would produce the same float as directly converting the f32 to f64 using `as`. For data that you plan to deserialize using Python's or JavaScript's number types, please produce it using f64 on the Rust side, or using f32 with a `serialize_with` attribute that handles the conversion to f64 during serialization.

**Comment by orlp** [comment] 2023-06-07 21:15
1. I don't think users would expect that `Foo` -> JSON text -> `serde_json::Value` -> `Foo` does not round-trip if they don't have the `arbitrary_precision` feature flag set. Is this really intended behavior?
2.  > It is not a goal that f32 -> json -> f64 would produce the same float as directly converting the f32 to f64 using as.

     Why not?

    >  For data that you plan to deserialize using Python's or JavaScript's number types, please produce it using f64 on the Rust side.
    
    Realistically speaking, what percentage of users will realize this is a problem?

**Comment by cemerick** [comment] 2023-08-09 04:35
I came across this issue when trying to figure out why a program of mine was suddenly emitting far more precise JSON floats, despite the underlying representation not changing a bit.

For the exact same Rust structs, this was the output we had gotten, and were continuing to expect:

```
{"ch":"S","b":[180.215,500.635,190.58298,513.361],"bl":[179.405,500.797,191.39297,518.797],"s":"s2","f":"f1"}
```

After what seemed like innocuous fiddling with our serde_json calls, we were suddenly getting:

```
{"b":[180.21499633789062,500.635009765625,190.58297729492188,513.3610229492188],"bl":[179.40499877929688,500.7969970703125,191.39297485351562,518.7969970703125],"ch":"S","f":"f1","s":"s2"}```

The types in question included a tuple of `f32`'s, so moving to use `to_value()` was the proximate cause of the change. (To be clear, the issue is not actually about precision, but about consistency of output over time. Big alarms go off any time there's any deviation from previously-recorded outputs.)

It cost us nothing to change those `f32`s to `f64`s, so the workaround is _fine_, but I guess count me in on being surprised by the difference.

**Comment by dtolnay** [comment] 2023-08-09 04:43
Overall I think this is working the way that I would want. In https://github.com/serde-rs/json/issues/1022#issuecomment-1581481044 I recommended some ways that a program can accommodate the desired use case, and if those are not a good fit, then it would need to use a different library.

**Closed by dtolnay** 2023-08-09 04:43 UTC
