### ISSUE TITLE
Prevent deserializing panic

### ISSUE THREAD

**Issue by hajsf** [serde-rs/json#552] opened 2019-07-10 18:09 UTC
I've defined `Location` as:

```rust
#[derive(Serialize, Deserialize, Debug)]
struct Location {
    unique_id: String,
    lat: f64,
    lon: f64,
    speed: f64
}
```

And receive data from server, which is deserialized as:

```rust
let deserialize: Location = serde_json::from_str(&msg).expect("error");
println!("id = {:?}", deserialize);
```

If the received data can not be deserialized to `Location`, the system is panic, I need it to give an error only, without being paniced!!

**Comment by dtolnay** [comment] 2019-07-10 18:16
serde_json::from_str returns an error. Your code is panicking:
https://doc.rust-lang.org/std/result/enum.Result.html#method.expect

**Comment by hajsf** [comment] 2019-07-10 18:48
@dtolnay 
I understand it is panicing, and I need to handle it as error instead of panic, I tried the below as well, but it does not work
 ```rust
           let deserialize = match serde_json::from_str(&msg){  
                Ok(v) => {v},
                Err(e) => {e}
            };
```

**Comment by hajsf** [comment] 2019-07-10 18:52
I was able to solve it as:
```rust
            let deserialize = match serde_json::from_str(msg.as_str()){  // msg.as_str()
                Ok(v) => {v},
                Err(e) => {Location{
                    unique_id: "".to_string(),
                    lat: 0.0,
                    lon: 0.0,
                    speed: 0.0
                }}
            };
                println!("id = {:?}", deserialize.unique_id);
```

**Comment by ssokolow** [comment] 2020-02-02 22:01
This should probably be closed as "not a bug in Serde".

**Closed** 2020-02-02 22:04 UTC
Labels: support
