### ISSUE TITLE
Feature request: Improve performance by SIMD

### ISSUE THREAD

**Issue by deeprobin** [serde-rs/json#699] opened 2020-07-21 09:31 UTC
Maybe it would be a way to accelerate serde-rs/json using SIMD¹ like the following C++ project does: [simdjson](https://github.com/simdjson/simdjson).

[1]: [Single Instruction Multiple Data](https://en.wikipedia.org/wiki/SIMD)

**Comment by dtolnay** [comment] 2020-07-21 11:43
Closing as a duplicate of #120.

**Closed by dtolnay** 2020-07-21 11:43 UTC
