### ISSUE TITLE
investigate SIMD JSON

### ISSUE THREAD

**Issue by Licenser** [serde-rs/json#519] opened 2019-02-26 20:13 UTC
Hi,
I came across this on twitter the other day: https://github.com/lemire/simdjson/blob/master/README.md it looks like an excellent application of SIMD on parsing json. Perhaps there are some tricks in there that serde could pick up :).

Note: Not a please do work! ticket, but I thought it might be worth keeping an eye on ;)

**Comment by dtolnay** [comment] 2019-02-26 20:19
Thanks! Closing as a duplicate of #120.

**Closed by dtolnay** 2019-02-26 20:19 UTC

**Comment by Licenser** [comment] 2019-02-26 20:20
The interestig part of simdjson is that it comes along with a paper explaining what they did and isn't a pure implementation.
